language: C
dist: trusty
env:
  global:
    - CI40_SDK="OpenWrt-SDK-0.10.4-pistachio-marduk_gcc-5.3.0_musl-1.1.14.Linux-x86_64"
    - CI40_SDK_URL="https://downloads.creatordev.io/pistachio/marduk/"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y gnupg git-core build-essential libssl-dev libncurses5-dev unzip gawk subversion mercurial
script:
  - export MAKEFILE_SOURCE_DIR="$TRAVIS_BUILD_DIR/feeds/ci40-weather-station"
  - export MAKEFILE_DEST_DIR="$HOME/build/custom_feed/ci40-weather-station"
  - export MAKEFILE_DEST_PATH="$MAKEFILE_DEST_DIR/Makefile"
  - mkdir -p $MAKEFILE_DEST_DIR
  - cp "$MAKEFILE_SOURCE_DIR/Makefile" $MAKEFILE_DEST_PATH
  - sed -i "s/^PKG_VERSION.*/PKG_VERSION:=HEAD/g" $MAKEFILE_DEST_PATH
  - sed -i "s#^PKG_SOURCE_URL.*#PKG_SOURCE_URL:=$TRAVIS_BUILD_DIR#g" $MAKEFILE_DEST_PATH
  - export CI40_FILE_URL="$CI40_SDK_URL$CI40_SDK.tar.bz2"
  - cd $HOME/build && wget $CI40_FILE_URL && tar xfj $CI40_SDK.tar.bz2
  - cd $CI40_SDK && echo src-link custom $HOME/build/custom_feed  >> feeds.conf.default
  - ./scripts/feeds update -a && ./scripts/feeds install -a
  - make package/ci40-weather-station/compile -j1
